Ebceys::Tests::Infrastructure::IntegrationTests::WebApplication::TestWebApplicationFactory-1-g
Uri Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.BaseAddress
The base address.
string Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.ServiceId
The service id.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.CreateWebHostBuilder.
bool Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.UseProductionAppSettings
Indicates that TestWebApplicationFactory<TStartup> should use production appsettings.json file.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.ConfigureWebHost.
override void Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.ConfigureWebHost(IWebHostBuilder builder)
References Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.ConfigureTestServices, Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.SetConfiguration, Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.UseProductionAppSettings.
override IWebHostBuilder Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.CreateWebHostBuilder()
References Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.CreateWebHostBuilder.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.CreateWebHostBuilder.
override TestServer Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.CreateServer(IWebHostBuilder builder)
override IHost Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.CreateHost(IHostBuilder builder)
virtual void Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.SetConfiguration(IConfigurationBuilder configurationBuilder)
Sets the configuration.
configurationBuilder The configuration builder.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.ConfigureWebHost.
void Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.ConfigureTestServices(IServiceCollection services)
Configures the test services.
services The services.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.ConfigureWebHost.
IWebHostBuilder Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.CreateWebHostBuilder(params string[] args)
References Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.TestWebApplicationFactory< TStartup >.ServiceId.