Ebceys::Infrastructure::Exceptions::ApiExceptionHelper
static TResult Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowNotFound< TResult >(string message, [CallerMemberName] string memberName="")
Throws not found exception.
message The message. memberName The member name. TResult ApiException
static TResult Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowNotFound< TResult, TException >(TException exception, [CallerMemberName] string memberName="")
Throws not found exception.
exception The inner exception. memberName The member name. TResult TException ApiException
static TResult Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowConflict< TResult >(string message, [CallerMemberName] string memberName="")
Throws the conflict exception.
message The message. memberName The member name. TResult ApiException
static TResult Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowConflict< TResult, TException >(TException exception, [CallerMemberName] string memberName="")
Throws conflict exception.
exception The exception. memberName The member name. TResult TException ApiException
static TResult Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowValidation< TResult >(ValidationProblemDetails problemDetails, [CallerMemberName] string memberName="")
Throws the validation exception.
problemDetails The problem details. memberName The member name. TResult ApiException
static TResult Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowException< TResult, TException >(TException exception, int statusCode=StatusCodes.Status500InternalServerError, [CallerMemberName] string memberName="")
Throws the exception.
exception The exception. statusCode The status code. memberName The member name. TResult TException ApiException
static void Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowException< TException >(TException exception, int statusCode=StatusCodes.Status500InternalServerError, [CallerMemberName] string memberName="")
Throws the exception.
exception The exception. statusCode The status code. memberName The member name. TException ApiException
static TResult Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException< TResult >(ProblemDetails? problemDetails, int? statusCode=null, [CallerMemberName] string memberName="")
Throws the api exception.
problemDetails The problem details. statusCode The status code. memberName The member name. TResult ApiException
References Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException.
static void Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException(ProblemDetails? problemDetails, int? statusCode=null, [CallerMemberName] string memberName="")
Throws the api exception.
problemDetails The problem details. statusCode The status code. memberName The member name. ApiException
Referenced by Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException< TError >, Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException< TResult >, Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException< TResult, TError >, Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException< TResult, TError >, Ebceys.Infrastructure.AuthorizationTestApplication.Controllers.AuthController.ValidateToken, Ebceys.Infrastructure.UnitTests.Exceptions.ApiExceptionTests.When_ApiException_With_EmptyProblemDetails_Result_CorrectFields, Ebceys.Infrastructure.UnitTests.Exceptions.ApiExceptionTests.When_ApiException_With_NullProblemDetails_Result_CorrectFields, Ebceys.Infrastructure.UnitTests.Exceptions.ApiExceptionTests.When_ApiException_With_RandomProblemDetails_Result_CorrectFields.
static void Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException< TError >(OperationResult< TError > operationResult, [CallerMemberName] string memberName="")
Throws the api exception created by operationResult .
operationResult The operation result. memberName The member name. TError The error. ApiException The api exception.
References Ebceys.Infrastructure.HttpClient.OperationResult< TError >.Error, Ebceys.Infrastructure.HttpClient.OperationResult< TError >.StatusCode, Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException.
static TResult Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException< TResult, TError >(OperationResult< TError > operationResult, [CallerMemberName] string memberName="")
Throws the api exception created by operationResult .
operationResult The operation result. memberName The member name. TError The error. TResult The result. ApiException The api exception.
References Ebceys.Infrastructure.HttpClient.OperationResult< TError >.Error, Ebceys.Infrastructure.HttpClient.OperationResult< TError >.StatusCode, Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException.
static TResult Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException< TResult, TError >(OperationResult< TResult, TError > operationResult, [CallerMemberName] string memberName="")
Throws the api exception created by operationResult .
operationResult The operation result. memberName The member name. TError The error. TResult The result. ApiException The api exception.
References Ebceys.Infrastructure.HttpClient.OperationResult< TResponse, TError >.Error, Ebceys.Infrastructure.HttpClient.OperationResult< TResponse, TError >.StatusCode, Ebceys.Infrastructure.Exceptions.ApiExceptionHelper.ThrowApiException.