Ebceys::Tests::Infrastructure::Helpers::TestCaseSources::TestCaseEnumerator-1-g
IEnumerable<TestCaseData> Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.Cases
Referenced by Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.GetEnumerator, Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.TestCaseEnumerator.
IEnumerable<(Func<TData?, TData?>, string)> Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.dataSource
Gets the data.
Referenced by Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.Enumerate, Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.EbTestDataInvalidExecutor< TEnumerator, TData >.override, Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.EbTestDataValidExecutor< TEnumerator, TData >.override.
Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.TestCaseEnumerator()
Initiates the new instance of TestCaseEnumerator<TData>.
References Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.Cases, Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.Enumerate.
IEnumerable<(Func< TData?, TData?>, string)>? TData baseData Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.GetData()
Referenced by Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.Enumerate, Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.EbTestDataInvalidExecutor< TEnumerator, TData >.override, Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.EbTestDataValidExecutor< TEnumerator, TData >.override.
IEnumerator< TestCaseData > Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.GetEnumerator()
References Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.Cases.
Referenced by Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.GetEnumerator.
IEnumerator IEnumerable. Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.GetEnumerator()
References Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.GetEnumerator.
IEnumerable< TestCaseData > Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.Enumerate()
References Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.dataSource, Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.GetData.
Referenced by Ebceys.Tests.Infrastructure.Helpers.TestCaseSources.TestCaseEnumerator< TData >.TestCaseEnumerator.