Ebceys::Infrastructure::HttpClient::ClientBase
const string Ebceys.Infrastructure.HttpClient.ClientBase.AuthorizationHeader
The authorization header key.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.GetAuthHeaders, Ebceys.Infrastructure.HttpClient.ClientBase.GetDefaultHeaders.
readonly IFlurlClient Ebceys.Infrastructure.HttpClient.ClientBase._client
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.ClientBase, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
readonly ILogger Ebceys.Infrastructure.HttpClient.ClientBase._logger
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.ClientBase, Ebceys.Infrastructure.HttpClient.ClientBase.LogRequest, Ebceys.Infrastructure.HttpClient.ClientBase.LogResponse.
readonly? Func<Task<string> > Ebceys.Infrastructure.HttpClient.ClientBase._tokenResolver
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.ClientBase, Ebceys.Infrastructure.HttpClient.ClientBase.GetDefaultHeaders.
string Ebceys.Infrastructure.HttpClient.ClientBase.ClientName
The client name to get it from IFlurlClientCache.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.ClientBase.
TimeSpan Ebceys.Infrastructure.HttpClient.ClientBase.Timeout
The default response awaiting timeout.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.ClientBase, Ebceys.Infrastructure.HttpClient.ClientBase.ConfigureClient.
TimeSpan Ebceys.Infrastructure.HttpClient.ClientBase.DelayBetweenRetries
The default delay between retries.
IAsyncPolicy<IFlurlResponse> Ebceys.Infrastructure.HttpClient.ClientBase.Policy
The default http request executing policy.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.ClientBase, Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync.
ISerializer Ebceys.Infrastructure.HttpClient.ClientBase.DefaultSerializer
The default request and response serializer.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.ConfigureClient, Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TRequest, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TRequest, TResponse, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PutJsonAsync< TRequest, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PutJsonAsync< TRequest, TResponse, TError >.
Ebceys.Infrastructure.HttpClient.ClientBase.ClientBase(IFlurlClientCache clientCache, ILoggerFactory loggerFactory, Func< string > baseUrlResolver, Func< Task< string > >? tokenResolver=null)
Initiates the new instance of ClientBase.
clientCache The client cache. baseUrlResolver The base url resolver. tokenResolver The token resolver. loggerFactory The logger factory.
References Ebceys.Infrastructure.HttpClient.ClientBase._client, Ebceys.Infrastructure.HttpClient.ClientBase._logger, Ebceys.Infrastructure.HttpClient.ClientBase._tokenResolver, Ebceys.Infrastructure.HttpClient.ClientBase.ClientName, Ebceys.Infrastructure.HttpClient.ClientBase.ConfigureClient, Ebceys.Infrastructure.HttpClient.ClientBase.Policy, Ebceys.Infrastructure.HttpClient.ClientBase.Timeout.
async Task< OperationResult< TResponse, TError > > Ebceys.Infrastructure.HttpClient.ClientBase.GetJsonAsync< TResponse, TError >(Action< Url > url, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends GET request with awaiting serialized body response.
url The url transform. headers The headers. token The cancellation token. TResponse The success response type. TError The error response type. The new instance of OperationResult<TResponse,TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TError > > Ebceys.Infrastructure.HttpClient.ClientBase.GetAsync< TError >(Action< Url > url, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends GET request.
url The url transform. headers The headers. token The cancellation token. TError The error response type. The new instance of OperationResult<TResponse,TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< Stream, TError > > Ebceys.Infrastructure.HttpClient.ClientBase.GetStreamAsync< TError >(Action< Url > url, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends GET request with awaiting Stream response.
url The url transform. headers The headers. token The cancellation token. TError The error response type. The new instance of OperationResult<TResponse,TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< byte[], TError > > Ebceys.Infrastructure.HttpClient.ClientBase.GetRawAsync< TError >(Action< Url > url, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends GET request with awaiting byte array response.
url The url transform. headers The headers. token The cancellation token. TError The error response type. The new instance of OperationResult<TResponse,TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TResponse, TError > > Ebceys.Infrastructure.HttpClient.ClientBase.DeleteJsonAsync< TResponse, TError >(Action< Url > url, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends DELETE request with awaiting serialized body response.
url The url transform. headers The headers. token The cancellation token. TResponse The success response type. TError The error response type. The new instance of OperationResult<TResponse,TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TError > > Ebceys.Infrastructure.HttpClient.ClientBase.DeleteAsync< TError >(Action< Url > url, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends DELETE request.
url The url transform. headers The headers. token The cancellation token. TError The error response type. The new instance of OperationResult<TResponse,TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TError > > Ebceys.Infrastructure.HttpClient.ClientBase.PostAsync< TError >(Action< Url > url, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends POST request.
url The url. headers The headers. token The cancellation token. TError The error response type. The new instance of OperationResult<TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TError > > Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TRequest, TError >(Action< Url > url, TRequest body, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends POST request with specified serialized body.
url The url. body The body. headers The headers. token The cancellation token. TRequest The request object type. TError The error response type. The new instance of OperationResult<TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.DefaultSerializer, Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TResponse, TError > > Ebceys.Infrastructure.HttpClient.ClientBase.PostStreamAsync< TResponse, TError >(Action< Url > url, Stream body, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends POST request with specified stream body and with awaiting TResponse deserialized response.
url The url. body The body. headers The headers. token The cancellation token. TError The error response type. TResponse The success response type. The new instance of OperationResult<TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TError > > Ebceys.Infrastructure.HttpClient.ClientBase.PostStreamAsync< TError >(Action< Url > url, Stream body, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends POST request with specified stream body.
url The url. body The body. headers The headers. token The cancellation token. TError The error response type. The new instance of OperationResult<TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TResponse, TError > > Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TRequest, TResponse, TError >(Action< Url > url, TRequest body, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends POST request with specified serialized body and with awaiting TResponse deserialized response.
url The url. body The body. headers The headers. token The cancellation token. TRequest The request object type. TError The error response type. TResponse The success response type. The new instance of OperationResult<TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.DefaultSerializer, Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TResponse, TError > > Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TResponse, TError >(Action< Url > url, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends POST request and with awaiting TResponse deserialized response.
url The url. headers The headers. token The cancellation token. TError The error response type. TResponse The success response type. The new instance of OperationResult<TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TError > > Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TError >(Action< Url > url, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends POST request.
url The url. headers The headers. token The cancellation token. TError The error response type. The new instance of OperationResult<TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TError > > Ebceys.Infrastructure.HttpClient.ClientBase.PutJsonAsync< TRequest, TError >(Action< Url > url, TRequest body, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends PUT request with specified serialized body.
url The url. body The body. headers The headers. token The cancellation token. TRequest The request object type. TError The error response type. The new instance of OperationResult<TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.DefaultSerializer, Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< OperationResult< TResponse, TError > > Ebceys.Infrastructure.HttpClient.ClientBase.PutJsonAsync< TRequest, TResponse, TError >(Action< Url > url, TRequest body, IDictionary< string, object >? headers=null, CancellationToken token=default)
Sends PUT request with specified serialized body and with awaiting TResponse deserialized response.
url The url. body The body. headers The headers. token The cancellation token. TRequest The request object type. TError The error response type. TResponse The success response type. The new instance of OperationResult<TError>.
References Ebceys.Infrastructure.HttpClient.ClientBase.DefaultSerializer, Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
async Task< IFlurlResponse > Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync(IFlurlRequest request, HttpMethod method, HttpCompletionOption completionOption=HttpCompletionOption.ResponseContentRead, CancellationToken token=default)
Executes the flurl request with Policy.
request The request. method The http method. completionOption The completion options. token The cancellation token. The Task which result contains the new instance of IFlurlResponse.
References Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithoutPolicyAsync, Ebceys.Infrastructure.HttpClient.ClientBase.LogRequest, Ebceys.Infrastructure.HttpClient.ClientBase.LogResponse, Ebceys.Infrastructure.HttpClient.ClientBase.Policy.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.DeleteAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.DeleteJsonAsync< TResponse, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.GetAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.GetJsonAsync< TResponse, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.GetRawAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.GetStreamAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TRequest, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TRequest, TResponse, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TResponse, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostStreamAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostStreamAsync< TResponse, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PutJsonAsync< TRequest, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PutJsonAsync< TRequest, TResponse, TError >.
virtual Task< IFlurlResponse > Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithoutPolicyAsync(Func< IFlurlRequest, CancellationToken, Task< IFlurlResponse > > func, IFlurlRequest request, CancellationToken token=default)
Executes the request delegate without policy.
func The delegate to execute. request The request to be executed. token The cancellation token. The Task which result contains the new instance of IFlurlResponse.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync.
void Ebceys.Infrastructure.HttpClient.ClientBase.ConfigureClient(IFlurlClientBuilder obj)
References Ebceys.Infrastructure.HttpClient.ClientBase.DefaultSerializer, Ebceys.Infrastructure.HttpClient.ClientBase.Timeout.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.ClientBase.
async Task< IFlurlRequest > Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest(Action< Url > url, IDictionary< string, object >? headers)
References Ebceys.Infrastructure.HttpClient.ClientBase._client, Ebceys.Infrastructure.HttpClient.ClientBase.GetDefaultHeaders.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.DeleteAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.DeleteJsonAsync< TResponse, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.GetAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.GetJsonAsync< TResponse, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.GetRawAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.GetStreamAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TRequest, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TRequest, TResponse, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostJsonAsync< TResponse, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostStreamAsync< TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PostStreamAsync< TResponse, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PutJsonAsync< TRequest, TError >, Ebceys.Infrastructure.HttpClient.ClientBase.PutJsonAsync< TRequest, TResponse, TError >.
async Task< Dictionary< string, object > > Ebceys.Infrastructure.HttpClient.ClientBase.GetDefaultHeaders(IDictionary< string, object >? additionalHeaders=null)
References Ebceys.Infrastructure.HttpClient.ClientBase._tokenResolver, Ebceys.Infrastructure.HttpClient.ClientBase.AuthorizationHeader.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.PrepareRequest.
void Ebceys.Infrastructure.HttpClient.ClientBase.LogRequest(HttpMethod method, IFlurlRequest request, string requestId)
References Ebceys.Infrastructure.HttpClient.ClientBase._logger.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync.
void Ebceys.Infrastructure.HttpClient.ClientBase.LogResponse(HttpMethod method, IFlurlResponse response, IFlurlRequest request, TimeSpan duration, string requestId)
References Ebceys.Infrastructure.HttpClient.ClientBase._logger.
Referenced by Ebceys.Infrastructure.HttpClient.ClientBase.ExecuteWithPolicyAsync.
static string Ebceys.Infrastructure.HttpClient.ClientBase.GetClientName(Type implementationType)
Gets the client name. With this name the client will get from IFlurlClientCache.
implementationType The client implementation type.
static Dictionary< string, object > Ebceys.Infrastructure.HttpClient.ClientBase.GetAuthHeaders(string token)
Gets the auth headers.
token The jwt. The new instance of request headers.
References Ebceys.Infrastructure.HttpClient.ClientBase.AuthorizationHeader.