Ebceys::Tests::Infrastructure::IntegrationTests::TestRoutingMessageHandler
readonly Dictionary<string, HostHandler> Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler._hosts
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.SendAsync.
RoutingMessageHandlerConfiguration Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.RouteConfiguration
The route configuration.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.SendAsync.
override async Task< HttpResponseMessage > Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
References Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler._hosts, Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.HostHandler, Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.RouteConfiguration.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.HostHandler.
class Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.HostHandler(HttpMessageHandler handler)
References Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.HostHandler, Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.SendAsync.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.HostHandler, Ebceys.Tests.Infrastructure.IntegrationTests.TestRoutingMessageHandler.SendAsync.