Ebceys::Tests::Infrastructure::IntegrationTests::WebApplication::RoutingMessageHandler
readonly Dictionary<string, Lazy<HostHandler> > Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler._hosts
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.AddHandler, Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.SendAsync.
Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.RoutingMessageHandler(IOptions< RoutingMessageHandlerConfiguration > opts)
References Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.AddHandler.
void Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.AddHandler(Uri origin, Func< HttpMessageHandler > handler)
References Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler._hosts, Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.HostHandler.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.AddHandler, Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.RoutingMessageHandler.
void Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.AddHandler(string origin, Func< HttpMessageHandler > handler)
References Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.AddHandler.
class Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.HostHandler(HttpMessageHandler innerHandler)
References Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.HostHandler, Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.SendAsync.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.AddHandler, Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.HostHandler, Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.ReplaceHttpHandlerByTest.
override Task< HttpResponseMessage > Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
References Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler._hosts, Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.ReplaceHttpHandlerByTest.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.HostHandler.
static bool Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.ReplaceHttpHandlerByTest(HttpMessageHandler? innerHandler, HostHandler handler)
References Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.HostHandler.
Referenced by Ebceys.Tests.Infrastructure.IntegrationTests.WebApplication.RoutingMessageHandler.SendAsync.