Ebceys::Infrastructure::Middlewares
class Ebceys.Infrastructure.Middlewares.ExceptionCatcherMiddleware(RequestDelegate next)
class Ebceys.Infrastructure.Middlewares.RequestLoggingMiddleware(RequestDelegate next, IOptions< HttpLoggingOptions > loggingOpts, ILogger< RequestLoggingMiddleware > logger)
The request logging middleware.
next The request delegate. logger The logger.
References Ebceys.Infrastructure.Middlewares.RequestLoggingMiddleware.
Referenced by Ebceys.Infrastructure.Middlewares.RequestLoggingMiddleware, Ebceys.Infrastructure.Tests.Middlewares.RequestLoggingMiddlewareTests.When_Requests_With_NoLoggingInAttr_Result_CatcherDontLogBodies, Ebceys.Infrastructure.Tests.Middlewares.RequestLoggingMiddlewareTests.When_Requests_With_NoLoggingInOpts_Result_CatcherDontLogBodies.
class Ebceys.Infrastructure.Middlewares.RequestMetricsMiddleware(RequestDelegate next)