Ebceys::Tests::Infrastructure::Helpers
partial class Ebceys.Tests.Infrastructure.Helpers.EbRandomizer(int seed=0)
The EbRandomizer class.
seed The seed.
References Ebceys.Tests.Infrastructure.Helpers.EbRandomizer.
Referenced by Ebceys.Tests.Infrastructure.Helpers.EbRandomizer, Ebceys.Tests.Infrastructure.IntegrationTests.ExternalServices.Containers.ExternalDependenciesExtensions.extension, Ebceys.Infrastructure.UnitTests.Helpers.EbRandomizerTests.GetJwts, Ebceys.Infrastructure.UnitTests.Helpers.EbRandomizerTests.Setup, Ebceys.Infrastructure.UnitTests.Helpers.EbRandomizerTests.When_RandomEmail_With_NotValidDomain_Result_InvalidOperationException, Ebceys.Infrastructure.Tests.ClientTests.ServiceSystemClientTests.When_ServicesStarted_With_HealthzStatusUnhealthy_Result_Unhealthy.