Ebceys::Infrastructure::AuthorizationTestApplication::BoundedContext
record Ebceys.Infrastructure.AuthorizationTestApplication.BoundedContext.GenerateTokenRequest(string UserName)
Referenced by Ebceys.Infrastructure.AuthorizationTestApplication.Client.IAppRabbitClient.GenerateTokenAsync, Ebceys.Infrastructure.AuthorizationTestApplication.Client.IAuthAppClient.GenerateTokenAsync, Ebceys.Infrastructure.AuthorizationTestApplication.Controllers.AuthController.GetToken, Ebceys.Infrastructure.TestApplication.Controllers.TestController.GetToken, Ebceys.Infrastructure.AuthorizationTestApplication.Controllers.AuthController.ValidateToken, Ebceys.Infrastructure.Tests.ClientTests.RabbitMqClientTests.When_GetJson_With_Result_Ok.
record Ebceys.Infrastructure.AuthorizationTestApplication.BoundedContext.GenerateTokenResponse(string Token)
Referenced by Ebceys.Infrastructure.AuthorizationTestApplication.Controllers.AuthController.GetToken.