Ebceys::Infrastructure::TestApplication::Commands
record Ebceys::Infrastructure::TestApplication::Commands.GetEntitiesCommandContext
Referenced by Ebceys.Infrastructure.TestApplication.Controllers.TestController.GetCommand, Ebceys.Infrastructure.TestApplication.Commands.GetEntitiesCommandResult, Ebceys.Infrastructure.TestApplication.Startup.
record Ebceys::Infrastructure::TestApplication::Commands.UpdateEntityCommandResult
Referenced by Ebceys.Infrastructure.TestApplication.Controllers.TestController.PutCommand, Ebceys.Infrastructure.TestApplication.Startup.
record Ebceys.Infrastructure.TestApplication.Commands.AddEntityCommandContext(string Name)
Referenced by Ebceys.Infrastructure.TestApplication.Commands.AddEntityCommandResult, Ebceys.Infrastructure.TestApplication.Controllers.TestController.PostCommand, Ebceys.Infrastructure.TestApplication.Startup.
record Ebceys.Infrastructure.TestApplication.Commands.AddEntityCommandResult(int Id, string Name)
References Ebceys.Infrastructure.TestApplication.Commands.AddEntityCommandContext, Ebceys.Infrastructure.TestApplication.DaL.DataModelContext.
Referenced by Ebceys.Infrastructure.TestApplication.Controllers.TestController.PostCommand, Ebceys.Infrastructure.TestApplication.Startup.
record Ebceys.Infrastructure.TestApplication.Commands.DeleteElementCommandContext(string Name)
Referenced by Ebceys.Infrastructure.TestApplication.Controllers.TestController.DeleteCommand, Ebceys.Infrastructure.TestApplication.Commands.DeleteElementCommandResult, Ebceys.Infrastructure.TestApplication.Startup.
record Ebceys.Infrastructure.TestApplication.Commands.DeleteElementCommandResult(bool Success)
References Ebceys.Infrastructure.TestApplication.DaL.DataModelContext, Ebceys.Infrastructure.TestApplication.Commands.DeleteElementCommandContext, Ebceys.Infrastructure.TestApplication.Commands.DeleteElementCommandResult.
Referenced by Ebceys.Infrastructure.TestApplication.Controllers.TestController.DeleteCommand, Ebceys.Infrastructure.TestApplication.Commands.DeleteElementCommandResult, Ebceys.Infrastructure.TestApplication.Startup.
record Ebceys.Infrastructure.TestApplication.Commands.GetEntitiesCommandResult(IReadOnlyCollection< TestTableDbo > Dbos)
References Ebceys.Infrastructure.TestApplication.DaL.DataModelContext, Ebceys.Infrastructure.TestApplication.Commands.GetEntitiesCommandContext, Ebceys.Infrastructure.TestApplication.Commands.GetEntitiesCommandResult.
Referenced by Ebceys.Infrastructure.TestApplication.Controllers.TestController.GetCommand, Ebceys.Infrastructure.TestApplication.Commands.GetEntitiesCommandResult, Ebceys.Infrastructure.TestApplication.Startup.
record Ebceys.Infrastructure.TestApplication.Commands.UpdateEntityCommandContext(string CurrentName, string NewName)
Referenced by Ebceys.Infrastructure.TestApplication.Controllers.TestController.PutCommand, Ebceys.Infrastructure.TestApplication.Startup.