Ebceys::Infrastructure::TestApplication::BoundedContext::Requests
record Ebceys.Infrastructure.TestApplication.BoundedContext.Requests.ChangeNameRequest(string NewName)
Referenced by Ebceys.Infrastructure.TestApplication.Controllers.TestController.PutCommand, Ebceys.Infrastructure.TestApplication.Client.Interfaces.ITestClient.PutCommandAsync, Ebceys.Infrastructure.TestApplication.Startup, Ebceys.Infrastructure.Tests.Middlewares.RequestLoggingMiddlewareTests.When_Requests_With_NoLoggingInAttr_Result_CatcherDontLogBodies.
record Ebceys.Infrastructure.TestApplication.BoundedContext.Requests.SomeBodyRequest(string Message)
Referenced by Ebceys.Infrastructure.TestApplication.Controllers.TestController.PostBody, Ebceys.Infrastructure.TestApplication.Client.Interfaces.ITestClient.PostBodyAsync, Ebceys.Infrastructure.TestApplication.Startup, Ebceys.Infrastructure.Tests.Middlewares.RequestLoggingMiddlewareTests.When_Requests_With_NoLoggingInOpts_Result_CatcherDontLogBodies.