Ebceys::Infrastructure::TestApplication::BoundedContext::Responses
record Ebceys.Infrastructure.TestApplication.BoundedContext.Responses.CommandResultResponse(IReadOnlyCollection< EntityResponseDto > Entities)
Referenced by Ebceys.Infrastructure.TestApplication.Controllers.TestController.GetCommand, Ebceys.Infrastructure.TestApplication.Controllers.TestController.PostCommand.
record Ebceys.Infrastructure.TestApplication.BoundedContext.Responses.EntityResponseDto(int Id, string Name)
References Ebceys.Infrastructure.TestApplication.BoundedContext.Responses.EntityResponseDto, Ebceys.Infrastructure.TestApplication.DaL.TestTableDbo.Id, Ebceys.Infrastructure.TestApplication.DaL.TestTableDbo.Name.
Referenced by Ebceys.Infrastructure.TestApplication.BoundedContext.Responses.EntityResponseDto, Ebceys.Infrastructure.TestApplication.Controllers.TestController.GetCommand, Ebceys.Infrastructure.TestApplication.Controllers.TestController.PostCommand.
record Ebceys.Infrastructure.TestApplication.BoundedContext.Responses.SomeBodyResponse(string Message)
Referenced by Ebceys.Infrastructure.TestApplication.Controllers.TestController.GetJson, Ebceys.Infrastructure.TestApplication.Controllers.TestController.GetQuery, Ebceys.Infrastructure.TestApplication.Controllers.TestController.PostBody.